runtime: java17
env: standard
# remember to use an instance class compatible with your scaling type
instance_class: B1
handlers:
  - url: .*
    script: auto
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
service_account: github-service-account@project-alpha-427516.iam.gserviceaccount.com