package org.core.backend.ticketapp.common.enums;

public enum EventCategoryEnum {
    ARTS_AND_CULTURE,
    CHARITY_AND_AID,
    COMMUNITY_WORK,
    EDUCATION_AND_CAREER,
    FESTIVAL,
    GOVERNMENT,
    MUSIC_AND_PERFORMANCES,
    CEREMONY,
    SPORTS_AND_FITNESS,
    FOOD_AND_DRINKS,
    INVESTMENTS,
    MEDIA_AND_FILM,
    MEET_AND_GREET,
    STARTUPS_AND_SMALL_BUSINESSES,
    TECHNOLOGY_AND_BUSINESS,
    WEEKEND_PARTY
}
