name: Build & Deploy to GCP AppEngine

on:
  push:
    branches:
      - backend
      - feature/*
      - adeshina/*
  pull_request:
    branches:
      - backend
      - feature/*
      - adeshina/*
    types: [closed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/checkout@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          # Leave other fields as placeholders

      - name: Build with Maven
        run: mvn clean install --file pom.xml  # Adjust path to your pom.xml
      - name: Clean up
        run: gcloud auth revoke --all
        
